### ISSUE TITLE
[idea] make a fancy DSL

### ISSUE THREAD

**Issue by jayunit100** [K8sbykeshed/k8s-service-lb-validator#14]
We could move tests like 
```
   CREATE service w/ spn label
   VERIFY svc1 it doesnt work
   CREATE service w/o spn label
   VERIFY svc2  it works
   UPDATE the 2n service w spn label
   VERIFY both services dont work
```

+ implement Go TestExample as well to make more readable

**Comment by jayunit100** [comment]
@mcluseau @knabben

**Comment by knabben** [comment]
https://github.com/K8sbykeshed/k8s-service-lb-validator/issues/46 - we could use klient and integrate the DSL on e2e fw
