### ISSUE TITLE
Should Be Able To Up And Down Service

### ISSUE THREAD

**Issue by knabben** [K8sbykeshed/k8s-service-lb-validator#17]
create svc1 in namespace
create svc2 in namespace
verify service svc1 be up
verify service svc2 be up
stop service
verify service svc1 be not up
verify service svc2 be still up
create service svc3 in namespace
verify service svc2 be still up
verify service svc3 be up

**Comment by yzaccc** [comment]
refer: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1036

**Comment by yzaccc** [comment]
create svc1 in namespace
create svc2 in namespace
verify service svc1 be up
verify service svc2 be up
stop service svc1
verify service svc1 be not up
verify service svc2 be still up
create service svc3 in namespace
verify service svc2 be still up
verify service svc3 be up

**Comment by knabben** [comment]
deep dive and live coding on next iteration !!

**Comment by knabben** [comment]
This issue can be closed since we have a lot of other ways to test them... too simple and already tested
